SET (EASTL_ROOT_DIR "deps/eastl" CACHE PATH "The root directory of EASTL")

FIND_PATH(EASTL_INCLUDE
	NAMES "EASTL"
	PATHS
	"${EASTL_ROOT_DIR}/include"
)

IF (EASTL_INCLUDE)
	SET (EASTL_FOUND TRUE)
	
	MESSAGE (STATUS "Found EASTL: ${EASTL_INCLUDE}")
ELSE ()
	SET (EASTL_FOUND FALSE)
	IF (EASTL_FIND_REQUIRED)
		MESSAGE (FATAL_ERROR "Could not find EASTL")
	ENDIF ()
ENDIF ()
