SET(GLFW_ROOT_DIR "deps/glfw" CACHE STRING "The root directory for the source of GLFW")

FIND_FILE(GLFW_INCLUDE
	NAMES "GLFW"
	PATHS
	"${GLFW_ROOT_DIR}/include"
)

IF (GLFW_INCLUDE)
	SET (GLFW_SOURCE_FOUND TRUE)
	
	MESSAGE (STATUS "Found GLFW: ${GLFW_INCLUDE}")
ELSE ()
	SET (GLFW_SOURCE_FOUND FALSE)
	IF (GLFWSource_FIND_REQUIRED)
		MESSAGE (FATAL_ERROR "Could not find GLFW")
	ENDIF ()
ENDIF ()
